Create ui themes
enastrazdina/limlapinas pull request #24
Opened 2020-02-24 12:33 UTC by enastrazdina

2020-02-24 13:06 UTC, uldisrudzitis requested changes

2020-02-24 13:06 UTC, uldisrudzitis commented on main.js
> +     newSticker.css({
No no no! Theme styles should be handled only by css.

2020-02-24 13:06 UTC, uldisrudzitis commented on index.html
> +    <button class="dark-mode">
What if we'll add another theme in future?

2020-02-24 13:06 UTC, uldisrudzitis commented on sass/theme.scss
> +  ::after {
use `&` here

2020-02-24 15:08 UTC, uldisrudzitis commented
Hint: https://sass-lang.com/documentation/values/maps
You should define settings for each template in a map.
Then loop through themes from this map and generate css.
There is basically two approaches you can solve this in SASS.
Also don't afraid from Google, there are plenty or examples and tutorials.

2020-02-26 15:45 UTC, uldisrudzitis commented on README.md
> +to cancel command c
`Press Ctrl-C to stop`

2020-02-26 15:46 UTC, uldisrudzitis commented on main.js
> +  $('dark-mode').on('click', darkMode);
Always check the changes you have made before commit. Remove redundant code.

2020-02-26 15:51 UTC, uldisrudzitis commented on sass/theme.scss
>  textarea {
Remove all the color definitions outside the theme loop (below this line).
Colors should be handled only by theme definitions.

2020-02-27 17:23 UTC, enastrazdina commented
<img width="200" alt="Screenshot 2020-02-27 at 19 20 58" src="https://user-images.githubusercontent.com/42971713/75468743-60124d00-5996-11ea-8dd6-407721f15d65.png">


somehow .css files are no longer ignored or they have a copy who needs to be pushed as well

2020-02-27 17:47 UTC, uldisrudzitis requested changes

2020-02-27 17:47 UTC, uldisrudzitis commented on main.js
> +    if ($(this).val() == 'epilepsy') {
Really bad practice with too many ifs. You can make this function more universal so that adding new themes do not require js modifications.

2020-02-27 17:47 UTC, uldisrudzitis commented on main.js
> +      $('body').removeClass().addClass('theme-epilepsy');
You are removing all the body classes here, you should take into account that there can be other classes, possibly added in the future. You should remove only those with `theme-` prefix

2020-03-03 12:20 UTC, uldisrudzitis requested changes

2020-03-03 12:20 UTC, uldisrudzitis commented on index.html
> +<body class="theme-light non-existing my-fake-theme-name">
remove those fake classes added for testing purpose only

2020-03-03 12:20 UTC, uldisrudzitis commented on index.html
> +      <select name="change themes" class="select-theme">
no need for `name` attribute here

2020-03-03 12:20 UTC, uldisrudzitis commented on main.js
> +    classList = $('body').attr('class').split(' ');
Add `var`

2020-03-03 12:25 UTC, uldisrudzitis commented
Possibly we need some margin between `add` and `settings` on small screens.

<img width="353" alt="Screenshot 2020-03-03 at 14 23 17" src="https://user-images.githubusercontent.com/864146/75775391-9109cd80-5d5a-11ea-8684-1e997d75ecd8.png">

2020-03-03 13:37 UTC, uldisrudzitis requested changes

2020-03-03 13:37 UTC, uldisrudzitis commented on sass/theme.scss
> +  padding: 0px;
no need for `px` is `0`.

2020-03-03 13:37 UTC, uldisrudzitis commented on sass/theme.scss
> +  .add {
No need to change in this breakpoint anything. Add button should be the same all the time.

2020-03-03 13:37 UTC, uldisrudzitis commented on sass/theme.scss
> +  text-align: left;
Just remove the text alignment for `.sidebar` we don't center anything anyway. After that you can remove all the alignments in sidebar children elements.

2020-03-03 14:14 UTC, uldisrudzitis approved these changes

2020-03-04 11:13 UTC, merged